version: '3.9'

services:
  scrapdealer-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:8080'
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
