version: '3.9'

services:
  scrapdealer-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapdealer-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SQL=Server=sqlserver;Database=ScrapDealerDB;User Id=sa;Password=Scr@pDe@1er!31372;TrustServerCertificate=True;
      - Redis__ConnectinString=redis:6379,password=123456
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=admin
      - Minio__SecretKey=admin123
      - Minio__BucketName=filestorage
      - Minio__UseSSL=false
    depends_on:
      - sqlserver
      - redis
      - minio

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: scrapdealer-sql
    environment:
      SA_PASSWORD: "Scr@pDe@1er!31372"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  redis:
    image: redis:7.0
    container_name: scrapdealer-redis
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: scrapdealer-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  sql_data:
  redis_data:
  minio_data:
